/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PassengerServicesAgent;

import Airport.AirportEcoSystem;
import Airport.Enterprise.Enterprise;
import Airport.Network.Network;
import Airport.Organization.Organization;
import Airport.UserAccount.UserAccount;
import Airport.WorkQueue.PassengerDisruptionRequest;
import Airport.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cohenpowell
 */
public class PassengerServicesAgentWorkAreaJPanel extends javax.swing.JPanel {

    JPanel container;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    AirportEcoSystem airport;

    /**
     * Creates new form PassengerServicesAgentWorkAreaJPanel
     */
    public PassengerServicesAgentWorkAreaJPanel(JPanel container, UserAccount account, Organization organization, Enterprise enterprise, AirportEcoSystem airport) {
        initComponents();
        this.container = container;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.airport = airport;
        populateTable();
    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0);

        // add disruption requests to table
        for (WorkRequest wr : organization.getWorkQueue().getWorkQueue()) {
            if (wr instanceof PassengerDisruptionRequest) {
                PassengerDisruptionRequest pdr = (PassengerDisruptionRequest) wr;
                Object[] row = new Object[5];
                row[0] = pdr.getWorkRequestId();
                row[1] = pdr.getDisruptionType();
                row[2] = pdr.getFlightNumber();
                row[3] = pdr.getAffectedPassengers();
                row[4] = pdr.getStatus();
                model.addRow(row);
            }
        }
    }

    private Organization findOrganization(String enterpriseName, String orgName) {
        for (Network n : airport.getNetworkList()) {
            for (Enterprise enterprise1 : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise1.getName().equals(enterpriseName)) {
                    for (Organization o : enterprise1.getOrganizationDirectory().getOrganizationList()) {
                        if (o.getName().equals(orgName)) {
                            return o;
                        }
                    }
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        lblDisruptionType = new javax.swing.JLabel();
        cmbDisruptionType = new javax.swing.JComboBox<>();
        lblFlightNumber = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        lblAffectedPassengers = new javax.swing.JLabel();
        txtAffectedPassengers = new javax.swing.JTextField();
        lblRequestedAction = new javax.swing.JLabel();
        txtRequestedAction = new javax.swing.JTextField();
        lblEstimatedCost = new javax.swing.JLabel();
        txtEstimatedCost = new javax.swing.JTextField();
        lblPassengerDetails = new javax.swing.JLabel();
        txtPassengerDetails = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitle.setText("Passenger Services Work Area");

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Disruption Type", "Flight #", "Passengers", "Status"
            }
        ));
        scrollPane.setViewportView(tblRequests);

        lblDisruptionType.setText("Disruption Type:");

        cmbDisruptionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancellation", "Delay", "Overbooking" }));

        lblFlightNumber.setText("Flight Number:");

        lblAffectedPassengers.setText("Affected Passengers:");

        lblRequestedAction.setText("Requested Action:");

        lblEstimatedCost.setText("Estimated Cost:");

        lblPassengerDetails.setText("Passenger Details:");

        btnSubmit.setText("Submit Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisruptionType)
                            .addComponent(lblFlightNumber)
                            .addComponent(lblAffectedPassengers)
                            .addComponent(lblRequestedAction)
                            .addComponent(lblEstimatedCost)
                            .addComponent(lblPassengerDetails))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDisruptionType, 0, 316, Short.MAX_VALUE)
                            .addComponent(txtFlightNumber)
                            .addComponent(txtAffectedPassengers)
                            .addComponent(txtRequestedAction)
                            .addComponent(txtEstimatedCost)
                            .addComponent(txtPassengerDetails)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(51, 51, 51)
                        .addComponent(btnRefresh)))
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisruptionType)
                    .addComponent(cmbDisruptionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNumber)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAffectedPassengers)
                    .addComponent(txtAffectedPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestedAction)
                    .addComponent(txtRequestedAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstimatedCost)
                    .addComponent(txtEstimatedCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassengerDetails)
                    .addComponent(txtPassengerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnRefresh))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String flightNumber = txtFlightNumber.getText().trim();
        String requestedAction = txtRequestedAction.getText().trim();
        String passengerDetails = txtPassengerDetails.getText().trim();

        if (flightNumber.isEmpty() || requestedAction.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Flight number and action are required");
            return;
        }

        int affectedPassengers;
        double estimatedCost;
        try {
            affectedPassengers = Integer.parseInt(txtAffectedPassengers.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number for passengers");
            return;
        }
        try {
            estimatedCost = Double.parseDouble(txtEstimatedCost.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cost needs to be a number");
            return;
        }

        Organization receiverOrg = findOrganization("Japan Airlines", "Flight Operations Division");
        if (receiverOrg == null) {
            JOptionPane.showMessageDialog(this, "Couldn't find Flight Operations org");
            return;
        }

        String disruptionType = (String) cmbDisruptionType.getSelectedItem();

        PassengerDisruptionRequest request = new PassengerDisruptionRequest(
            disruptionType, flightNumber, affectedPassengers, requestedAction,
            estimatedCost, passengerDetails, organization, receiverOrg,
            account.getEmployee().getName()
        );

        organization.getWorkQueue().addWorkRequest(request);
        receiverOrg.getWorkQueue().addWorkRequest(request);

        JOptionPane.showMessageDialog(this, "Request submitted", "Done", JOptionPane.INFORMATION_MESSAGE);
        txtFlightNumber.setText("");
        txtAffectedPassengers.setText("");
        txtRequestedAction.setText("");
        txtEstimatedCost.setText("");
        txtPassengerDetails.setText("");
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbDisruptionType;
    private javax.swing.JLabel lblAffectedPassengers;
    private javax.swing.JLabel lblDisruptionType;
    private javax.swing.JLabel lblEstimatedCost;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JLabel lblPassengerDetails;
    private javax.swing.JLabel lblRequestedAction;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextField txtAffectedPassengers;
    private javax.swing.JTextField txtEstimatedCost;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtPassengerDetails;
    private javax.swing.JTextField txtRequestedAction;
    // End of variables declaration//GEN-END:variables
}
