/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import Airport.AirportEcoSystem;
import Airport.Enterprise.Enterprise;
import Airport.Network.Network;
import Airport.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.JPanel;

/**
 *
 * @author fredtriest
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel container;
    AirportEcoSystem system;
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel container, AirportEcoSystem system) {
        initComponents();
        this.container = container;
        this.system = system;
        populateTree();
    }
    
    public void populateTree() {
        
        // Get the tree model (what displays in the JTree) and root node (gets top level node of the tree)
        DefaultTreeModel model = (DefaultTreeModel)airportEcoSystemJTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        
        // Clear existing nodes so we start fresh every time
        root.removeAllChildren();
        
        // Set root node text
        root.setUserObject("Airport EcoSystem");
        
        // 3 nested loops - each level creates a new DefaultMutableTreeNode and adds to the parent node
        // Loop through each network
        for (Network network : system.getNetworkList()) {
            DefaultMutableTreeNode networkNode = new DefaultMutableTreeNode(network.getName());
            root.add(networkNode);
            
            // Loop through each enterprise in the new network
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                DefaultMutableTreeNode enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.add(enterpriseNode);
                
                // Loop through each organization in the enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    DefaultMutableTreeNode organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.add(organizationNode);
            }
        }
    }
        
    // Reload the model so JTree refreshes and displays the updated nodes
    model.reload();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        airportEcoSystemJTree = new javax.swing.JTree();
        btnManageEnterprises = new javax.swing.JButton();
        btnManageEnterpriseAdmins = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitle.setText("System Admin Work Area ");

        scrollPane.setViewportView(airportEcoSystemJTree);

        btnManageEnterprises.setText("Manage Enterprises");
        btnManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterprisesActionPerformed(evt);
            }
        });

        btnManageEnterpriseAdmins.setText("Manage Enterprise Admins");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(465, Short.MAX_VALUE)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageEnterpriseAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageEnterprises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(314, 314, 314))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageEnterpriseAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterprisesActionPerformed
        
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(container, system);
        container.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);

    }//GEN-LAST:event_btnManageEnterprisesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree airportEcoSystemJTree;
    private javax.swing.JButton btnManageEnterpriseAdmins;
    private javax.swing.JButton btnManageEnterprises;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
