/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;

import Airport.AirportEcoSystem;
import Airport.Employee.Employee;
import Airport.Enterprise.Enterprise;
import Airport.Organization.Organization;
import Airport.Role.Role;
import Airport.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fredtriest
 */
public class ManageUsersJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise enterprise;
    private AirportEcoSystem airport;
    /**
     * Creates new form ManageUsersJPanel
     */
    public ManageUsersJPanel(JPanel container, Enterprise enterprise, AirportEcoSystem airport) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.airport = airport;
        populateOrganizationComboBox();
        populateRoleComboBox();
        populateTable();
    }
    
    // Populates organization picklist with the enterprise's organizations
    public void populateOrganizationComboBox() {
        cmbOrganization.removeAllItems();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            cmbOrganization.addItem(org.getName());
        }
    }
    
    // Populates role picklist based on the selected organization's supported roles
    public void populateRoleComboBox() {
        cmbRole.removeAllItems();
        String selectedOrgName = (String) cmbOrganization.getSelectedItem();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getName().equals(selectedOrgName)) {
                for (Role role : org.getSupportedRole()) {
                    cmbRole.addItem(role.toString());
                }
                break;
            }
        }
    }
    
    // Display all users in the enterprise and all orgs
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);
        
        // Enterprise users
        for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = {ua.getUserAccountId(), ua.getEmployee().getName(),ua.getUsername(), ua.getRole().toString(), "Enterprise Level"};
            model.addRow(row);
        }
        
        // Organization users
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                Object[] row = {ua.getUserAccountId(), ua.getEmployee().getName(), ua.getUsername(), ua.getRole().toString(), org.getName()};
                model.addRow(row);
            }
        }
    }
    
    public void clearFields() {
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtTitle.setText("");
        txtAge.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        cmbRole = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblJobTitle = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBacks = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitle.setText("Manage Users");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Role", "Organization"
            }
        ));
        scrollPane.setViewportView(tblUsers);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblRole.setText("Role:");

        lblOrganization.setText("Organization:");

        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone:");

        lblJobTitle.setText("Title:");

        lblAge.setText("Age:");

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBacks.setText("<< Back");
        btnBacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblRole)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblName)
                                                    .addGap(10, 10, 10)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEmail)
                                                .addGap(12, 12, 12)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPhone)
                                            .addGap(8, 8, 8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblJobTitle)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addGap(22, 22, 22)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBacks)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAge)
                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRole, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPassword)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtPassword))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOrganization)
                                            .addComponent(lblUsername))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbOrganization, 0, 165, Short.MAX_VALUE)
                                            .addComponent(txtUsername)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole)
                    .addComponent(lblOrganization)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnBacks))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        // Get selected org
        String selectedOrgName = (String) cmbOrganization.getSelectedItem();
        Organization selectedOrg = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getName().equals(selectedOrgName)) {
                selectedOrg = org;
                break;
            }
        }
        
        if (selectedOrg == null) {
            JOptionPane.showMessageDialog(null, "You must select a valid organization", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get selected role
        String selectedRoleName = (String) cmbRole.getSelectedItem();
        Role selectedRole = null;
        for (Role role : selectedOrg.getSupportedRole()) {
            if (role.toString().equals(selectedRoleName)) {
                selectedRole = role;
                break;
            }
        }
        
        if (selectedRole == null) {
            JOptionPane.showMessageDialog(null, "You must select a valid role", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirm fields are valid
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String title = txtTitle.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String ageText = txtAge.getText().trim();
        
        if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || title.isEmpty()|| username.isEmpty() || password.isEmpty() || ageText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You must fill in all of the fields", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int age;
        try {
            age = Integer.parseInt(ageText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age can only be a number", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!selectedOrg.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(null, "The username already exists", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create user account and employee in the selected org
        Employee employee = selectedOrg.getEmployeeDirectory().createEmployee(name, email, phone, title, age);
        selectedOrg.getUserAccountDirectory().createUserAccount(username, password, employee, selectedRole);
        
        populateTable();
        clearFields();
        JOptionPane.showMessageDialog(null, "User successfully created", "Success", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a user to update", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String title = txtTitle.getText().trim();
        String ageText = txtAge.getText().trim();
        
        if (name.isEmpty() && email.isEmpty() && phone.isEmpty() && title.isEmpty() && ageText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You must enter at least one field to update", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String accountId = (String) tblUsers.getValueAt(selectedRow, 0);
        
        // Search the enterprise then orgs for matching the account
        for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getUserAccountId().equals(accountId)) {
                updateEmployee(ua, name, email, phone, title, ageText);
                return;
            }
        }
        
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getUserAccountId().equals(accountId)) {
                    updateEmployee(ua, name, email, phone, title, ageText);
                    return;
                }
            }
        }
    }
    
    // Extracted update logic to avoid repeating it in two places
    private void updateEmployee(UserAccount ua, String name, String email, String phone, String title, String ageText) {
        if (!name.isEmpty()) ua.getEmployee().setName(name);
        if (!email.isEmpty()) ua.getEmployee().setEmail(email);
        if (!phone.isEmpty()) ua.getEmployee().setPhone(phone);
        if (!title.isEmpty()) ua.getEmployee().setTitle(title);
        if (!ageText.isEmpty()) {
            try {
                ua.getEmployee().setAge(Integer.parseInt(ageText));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "The age must be a number", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        populateTable();
        clearFields();
        JOptionPane.showMessageDialog(null, "The user has been successfully updated", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a user to delete", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
            return;
        
        
        String accountId = (String) tblUsers.getValueAt(selectedRow, 0);
        
        // Search enterprise first
        for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getUserAccountId().equals(accountId)) {
                enterprise.getUserAccountDirectory().getUserAccountList().remove(ua);
                populateTable();
                JOptionPane.showMessageDialog(null, "You have successfully deletedd this user", "Success", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        
        // Search org level next
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getUserAccountId().equals(accountId)) {
                    org.getUserAccountDirectory().getUserAccountList().remove(ua);
                    populateTable();
                    JOptionPane.showMessageDialog(null, "You have successfully delete this user", "Success", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacksActionPerformed
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.show(container, "workArea");
    }//GEN-LAST:event_btnBacksActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        
        populateRoleComboBox();
        
    }//GEN-LAST:event_cmbOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBacks;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbOrganization;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
